test:
    pytest tests
sudo: false
language: python
cache: pip
matrix:
  include:
    - python: 2.7
      env:
      - TOXENV=py27
    - python: 3.5
      env:
      - TOXENV=py35
    - python: 3.6
      env:
      - TOXENV=py36
notifications:
  email:
    recipients:
      - dxdstudio@gmail.com
    on_failure: always
install:
    - pip install --upgrade pip setuptools tox
    - pip install .
script: tox -e $TOXENV
after_success:
  coveralls
